# Generated by Django 6.0.2 on 2026-02-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('cover', models.ImageField(upload_to='covers/')),
                ('file', models.FileField(upload_to='books/')),
                ('file_size', models.BigIntegerField()),
                ('format', models.CharField(default='fb2', max_length=10)),
                ('flibusta_id', models.CharField(max_length=100, null=True, unique=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(default='ru', max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
