# Generated by Django 6.0 on 2026-02-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='last_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='progress_percent',
            field=models.FloatField(default=0),
        ),
    ]
